app/Http/routes.php
    Route::delete('author/{id}', ['as'=>'author.destroy', 'uses'=>'AuthorController@destroy']);
    Route::get('authors/datatables', ['as'=>'author.indexdataTables', 'uses'=>'AuthorController@indexDataTables']);
    Route::get('authors/index-data', ['as'=>'author.indexData', 'uses'=>'AuthorController@indexData']);
    Route::get('author/autocomplete', ['as'=>'author.autoComplete', 'uses'=>'AuthorController@autoComplete']);

    Route::get('languages', ['as'=>'language.index', 'uses'=>'LanguageController@index']);
    Route::get('language/create', ['as'=>'language.create', 'uses'=>'LanguageController@create']);
    Route::post('language', ['as'=>'language.store', 'uses'=>'LanguageController@store']);
    Route::get('language/{id}', ['as'=>'language.show', 'uses'=>'LanguageController@show']);
    Route::get('language/{id}/edit', ['as'=>'language.edit', 'uses'=>'LanguageController@edit']);
    Route::patch('language/{id}', ['as'=>'language.update', 'uses'=>'LanguageController@update']);
    Route::delete('language/{id}', ['as'=>'language.destroy', 'uses'=>'LanguageController@destroy']);

    Route::get('publishers', ['as'=>'publisher.index', 'uses'=>'PublisherController@index']);
    Route::get('publisher/create', ['as'=>'publisher.create', 'uses'=>'PublisherController@create']);
    Route::post('publisher', ['as'=>'publisher.store', 'uses'=>'PublisherController@store']);
    Route::get('publisher/{id}', ['as'=>'publisher.show', 'uses'=>'PublisherController@show']);
    Route::get('publisher/{id}/edit', ['as'=>'publisher.edit', 'uses'=>'PublisherController@edit']);
    Route::patch('publisher/{id}', ['as'=>'publisher.update', 'uses'=>'PublisherController@update']);
    Route::delete('publisher/{id}', ['as'=>'publisher.destroy', 'uses'=>'PublisherController@destroy']);
    Route::get('publisher/autocomplete', ['as'=>'publisher.autoComplete', 'uses'=>'PublisherController@autoComplete']);

    Route::get('tag/autocomplete', ['as'=>'tag.autoComplete', 'uses'=>'TagController@autoComplete']);

    Route::get('currencies', ['as'=>'currency.index', 'uses'=>'CurrencyController@index']);
    Route::get('currency/create', ['as'=>'currency.create', 'uses'=>'CurrencyController@create']);
    Route::post('currency', ['as'=>'currency.store', 'uses'=>'CurrencyController@store']);
    Route::get('currency/{code}', ['as'=>'currency.show', 'uses'=>'CurrencyController@show']);
    Route::get('currency/{code}/edit', ['as'=>'currency.edit', 'uses'=>'CurrencyController@edit']);
    Route::patch('currency/{code}', ['as'=>'currency.update', 'uses'=>'CurrencyController@update']);
    Route::delete('currency/{code}', ['as'=>'currency.destroy', 'uses'=>'CurrencyController@destroy']);

    Route::get('channels', ['as'=>'channel.index', 'uses'=>'ChannelController@index']);
    Route::get('channel/create', ['as'=>'channel.create', 'uses'=>'ChannelController@create']);
    Route::post('channel', ['as'=>'channel.store', 'uses'=>'ChannelController@store']);
    Route::get('channel/{id}', ['as'=>'channel.show', 'uses'=>'ChannelController@show']);
    Route::get('channel/{id}/edit', ['as'=>'channel.edit', 'uses'=>'ChannelController@edit']);
    Route::patch('channel/{id}', ['as'=>'channel.update', 'uses'=>'ChannelController@update']);
    Route::delete('channel/{id}', ['as'=>'channel.destroy', 'uses'=>'ChannelController@destroy']);

    Route::get('books', ['as'=>'book.index', 'uses'=>'BookController@index']);
    Route::get('books/index-data', ['as'=>'book.indexData', 'uses'=>'BookController@indexData']);
    Route::get('book/create', ['as'=>'book.create', 'uses'=>'BookController@create']);
    Route::post('book', ['as'=>'book.store', 'uses'=>'BookController@store']);
    Route::get('book/{id}', ['as'=>'book.show', 'uses'=>'BookController@show']);
    Route::get('book/{id}/add-copy', ['as'=>'book.addCopy', 'uses'=>'BookController@addCopy']);
    Route::get('book/{id}/edit', ['as'=>'book.edit', 'uses'=>'BookController@edit']);

    Route::get('book/{id}/calculations', ['as'=>'book.indexCalculation', 'uses'=>'BookController@indexCalculation']);
    Route::post('book/{id}/recalculate', ['as'=>'book.recalculate', 'uses'=>'BookController@recalculate']);

    Route::patch('book/{id}', ['as'=>'book.update', 'uses'=>'BookController@update']);
    Route::delete('book/{id}', ['as'=>'book.destroy', 'uses'=>'BookController@destroy']);
    Route::get('book/autocomplete', ['as'=>'book.autoComplete', 'uses'=>'BookController@autoComplete']);


    Route::get('book/{book_id}/amazon-data', ['as'=>'amazonData.index', 'uses'=>'AmazonDataController@index']);
    Route::post('book/{book_id}/amazon-data/refresh', ['as'=>'amazonData.refresh', 'uses'=>'AmazonDataController@refresh']);

    Route::get('book/{book_id}/ebay/alerts', ['as'=>'ebayItem.index', 'uses'=>'EbayItemController@index']);
    Route::get('book/{book_id}/ebay/alerts-data', ['as'=>'ebayItem.indexData', 'uses'=>'EbayItemController@indexData']);

    Route::get('book/{book_id}/ebay/live-search', ['as'=>'ebayItem.liveSearch', 'uses'=>'EbayItemController@liveSearch']);
    Route::post('book/{book_id}/ebay/alerts/refresh', ['as'=>'ebayItem.refresh', 'uses'=>'EbayItemController@refresh']);
    Route::get('ebay-item/{id}/edit', ['as'=>'ebayItem.edit', 'uses'=>'EbayItemController@edit']);
    Route::patch('ebay-item/{id}', ['as'=>'ebayItem.update', 'uses'=>'EbayItemController@update']);
    Route::post('ebay-item/{id}/change-status', ['as'=>'ebayItem.changeStatus', 'uses'=>'EbayItemController@changeStatus']);
    Route::post('ebay-items/mass-action', ['as'=>'ebayItem.massAction', 'uses'=>'EbayItemController@massAction']);
    Route::get('ebay-item/{id}', ['as'=>'ebayItem.show', 'uses'=>'EbayItemController@show']);


    Route::get('book/{book_id}/keywords', ['as'=>'keyword.index', 'uses'=>'KeywordController@index']);
    Route::get('book/{book_id}/keyword/create', ['as'=>'keyword.create', 'uses'=>'KeywordController@create']);
    Route::post('book/{book_id}/keyword', ['as'=>'keyword.store', 'uses'=>'KeywordController@store']);
    Route::get('keyword/{id}/edit', ['as'=>'keyword.edit', 'uses'=>'KeywordController@edit']);
    Route::patch('keyword/{id}', ['as'=>'keyword.update', 'uses'=>'KeywordController@update']);
    Route::delete('keyword/{id}', ['as'=>'keyword.destroy', 'uses'=>'KeywordController@destroy']);

    Route::get('conditions', ['as'=>'condition.index', 'uses'=>'ConditionController@index']);
    Route::get('condition/create', ['as'=>'condition.create', 'uses'=>'ConditionController@create']);
    Route::post('condition', ['as'=>'condition.store', 'uses'=>'ConditionController@store']);
    Route::get('condition/{id}', ['as'=>'condition.show', 'uses'=>'ConditionController@show']);
    Route::get('condition/{id}/edit', ['as'=>'condition.edit', 'uses'=>'ConditionController@edit']);
    Route::patch('condition/{id}', ['as'=>'condition.update', 'uses'=>'ConditionController@update']);
    Route::delete('condition/{id}', ['as'=>'condition.destroy', 'uses'=>'ConditionController@destroy']);

    Route::get('locations', ['as'=>'location.index', 'uses'=>'LocationController@index']);
    Route::get('location/create', ['as'=>'location.create', 'uses'=>'LocationController@create']);
    Route::post('location', ['as'=>'location.store', 'uses'=>'LocationController@store']);
    Route::get('location/{id}', ['as'=>'location.show', 'uses'=>'LocationController@show']);
    Route::get('location/{id}/edit', ['as'=>'location.edit', 'uses'=>'LocationController@edit']);
    Route::patch('location/{id}', ['as'=>'location.update', 'uses'=>'LocationController@update']);
    Route::delete('location/{id}', ['as'=>'location.destroy', 'uses'=>'LocationController@destroy']);

    Route::get('copies', ['as'=>'copy.index', 'uses'=>'CopyController@index']);
    Route::get('copies/sold', ['as'=>'copy.indexSold', 'uses'=>'CopyController@indexSold']);
    Route::get('copy/create', ['as'=>'copy.create', 'uses'=>'CopyController@create']);
    Route::post('copy', ['as'=>'copy.store', 'uses'=>'CopyController@store']);
    Route::get('copy/{id}', ['as'=>'copy.show', 'uses'=>'CopyController@show']);
    Route::get('copy/{id}/edit', ['as'=>'copy.edit', 'uses'=>'CopyController@edit']);
    Route::patch('copy/{id}', ['as'=>'copy.update', 'uses'=>'CopyController@update']);
    Route::delete('copy/{id}', ['as'=>'copy.destroy', 'uses'=>'CopyController@destroy']);

    Route::get('copy/{id}/purchase/edit', ['as'=>'copy.purchaseEdit', 'uses'=>'CopyController@purchaseEdit']);
    Route::patch('copy/{id}/purchase', ['as'=>'copy.purchaseUpdate', 'uses'=>'CopyController@purchaseUpdate']);
    Route::get('copy/{id}/sale/edit', ['as'=>'copy.saleEdit', 'uses'=>'CopyController@saleEdit']);
    Route::patch('copy/{id}/sale', ['as'=>'copy.saleUpdate', 'uses'=>'CopyController@saleUpdate']);

    Route::get('schedule-items', ['as'=>'scheduleItem.index', 'uses'=>'ScheduleItemController@index']);
    Route::get('schedule-item/create/{taskType}', ['as'=>'scheduleItem.create', 'uses'=>'ScheduleItemController@create']);
    Route::post('schedule-item/{taskType}', ['as'=>'scheduleItem.store', 'uses'=>'ScheduleItemController@store']);
    Route::get('schedule-item/{id}', ['as'=>'scheduleItem.show', 'uses'=>'ScheduleItemController@show']);
    Route::get('schedule-item/{id}/edit', ['as'=>'scheduleItem.edit', 'uses'=>'ScheduleItemController@edit']);
    Route::patch('schedule-item/{id}', ['as'=>'scheduleItem.update', 'uses'=>'ScheduleItemController@update']);
    Route::delete('schedule-item/{id}', ['as'=>'scheduleItem.destroy', 'uses'=>'ScheduleItemController@destroy']);


    Route::group(['prefix' => '{type}/{functionable_id}'], function($group) {
        Route::get('math-functions', ['as'=>'mathFunction.index', 'uses'=>'MathFunctionController@index']);
        Route::get('math-function/create', ['as'=>'mathFunction.create', 'uses'=>'MathFunctionController@create']);

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model {
    use \Conner\Tagging\Taggable;

    protected $fillable = ['isbn_10', 'isbn_13', 'currency_code', 'cover_price', 'language_id', 'publisher_id', 'series',
        'special_type_id', 'year', 'author_id', 'title', 'origin_year', 'origin_title', 'notes',
        'suggested_sale_price', 'price_limit', 'asin', 'aggregates'

    ];

    public function getISBN()
    {
        return $this->isbn_13 ? $this->isbn_13 : ($this->isbn_10 ? $this->isbn_10 : null);
    }

    public function getDecadeAttribute()
    {
        if ($this->year === null) return null;
        $startDecade = $this->year - ($this->year % 10);
        return $startDecade.'-'.($startDecade + 9);
    }

    public function getPriceLimitAttribute()
    {
        //IF MAX SALE PRICE is > EUR 15 = price limit is 35 percent of AVERAGE SALE PRICE
        /*
        if ($this->max_price > 15) {
            return round($this->avg_price / 100 * 35, 2);
        }
        */
        return null;
    }

    public function getLabelAttribute() {
        $label = '"' . $this->title . '"';
        if ($this->author !== null) $label .= ' ' . $this->author->name;
        if ($this->year !== null) $label .= ' (' . $this->year . ')';
        return $label;
    }

    public function setCurrencyCodeAttribute($value)
    {
        $this->attributes['currency_code'] = $value !== '' ? $value : null;
    }

    public function setCoverPriceAttribute($value)
    {
        $this->attributes['cover_price'] = $value !== '' ? $value : null;
    }

    public function setYearAttribute($value)
    {
        $this->attributes['year'] = $value !== '' ? $value : null;
    }

    public function setOriginYearAttribute($value)
    {
        $this->attributes['origin_year'] = $value !== '' ? $value : null;
    }

    public function setLanguageIdAttribute($value)
    {
        $this->attributes['language_id'] = $value !== '' ? $value : null;
    }

    public function images()
    {
        return $this->morphMany('App\Image', 'imageable');
    }

    public function currency()
    {
        return $this->belongsTo('App\Currency', 'currency_code', 'code');
    }

    public function getBookCurrencyAttribute() {
        return $this->currency ? $this->currency : Currency::appCurrency();
    }

    public function mathFunctions()
    {
        return $this->morphMany('App\MathFunction', 'functionable');
    }

    public function language()
    {
        return $this->belongsTo('App\Language');
    }

    public function publisher()
    {
        return $this->belongsTo('App\Publisher');
    }

    public function author()
    {
        return $this->belongsTo('App\Author');
    }

    public function copies()
    {
        return $this->hasMany('App\Copy');
    }

    public function soldCopies()
    {
        return $this->hasMany('App\Copy')
            ->select('copies.*')
            ->join('sales', 'sales.copy_id', '=', 'copies.id');
    }

    public function remainCopies()
    {
        return $this->hasMany('App\Copy')
            ->select('copies.*')
            ->leftJoin('sales', 'sales.copy_id', '=', 'copies.id')
            ->whereNull('sales.id');
    }


    public function keywords() {
        return $this->hasMany('App\Keyword');
    }

    public function amazonData()
    {
        return $this->hasMany('App\AmazonData');
    }

    public function ebayItems()
    {
        return $this->hasMany('App\EbayItem');
    }

    protected static function boot() {
        parent::boot();

        static::deleting(function($model) {
            foreach($model->images as $image) {
                //delete as model with clearing attaches
                $image->delete();
            }
        });
    }

    public function calcAggregatePrices() {
        $ebayItems = $this->ebayItems()
            ->approved()
            ->with('currency')
            ->get();
        $count = count($ebayItems);
        $min = $sum = $max = $avg = null;
        $count_1 = $count_2 = 0;
        $sum_1 = $avg_1 = $sum_2 = $avg_2 = $max2 = null;
        foreach($ebayItems as $ebayItem) {
            $bookCurrencyPrice = $ebayItem->currency->toCurrency($this->book_currency, $ebayItem->price);
            $max = max($max, $bookCurrencyPrice);
            $min = $min !== null ? min($min, $bookCurrencyPrice) : $bookCurrencyPrice;
            $sum += $bookCurrencyPrice;

            if ($ebayItem->first_edition) {
                $count_1++;
                $sum_1 += $bookCurrencyPrice;
            } else {
                $count_2++;
                $sum_2 += $bookCurrencyPrice;

                $max2 = max($max2, $bookCurrencyPrice);
            }
        }

        //load to external and than save
        //https://laravel.com/docs/5.1/eloquent-mutators#attribute-casting
        // $aggregates = $this->aggregates;
        // $aggregates['test'] = ...
        // $this->aggregates = $aggregates;

        $this->aggregates = [
            'max_price' => $max,
            'avg_price' => $count ? $sum / $count : null,
            'min_price' => $min,

            'avg_1_price' => $count_1 ? $sum_1 / $count_1 : null,
            'avg_2_price' => $count_2 ? $sum_2 / $count_2 : null,
            'max_2_price' => $max2,
        ];
    }

    protected $casts = [
        'aggregates' => 'array',
    ];

}

resources/views/book/_actions.blade.php
<a href="{{ route('book.indexCalculation', $model->id) }}" class="btn btn-default">Calculations</a>
<a href="{{ route('book.show', $model->id) }}" class="btn btn-info">Info</a>

resources/views/book/_autocomplete.blade.php
<div class="clearfix">
    <div>"{{ $model->title }}" {{ $model->author->name }}</div>
    <div>{{ $model->publisher->name }} {{ $model->year }}</div>
</div>

resources/views/book/calculation.blade.php
@extends('layouts.default')

@section('content')
    <div class="page-bar">
        @include('parts.breadcrumbs', ['breadcrumbs' => [
            ['label' => 'Books', 'link' => route('book.index')],
            ['label' => $book->label, 'link' => route('book.show', $book->id)],
            'Calculations'
        ]])
    </div>

    <h3>Calculations</h3>
    <div class="portlet light bordered">
        <div class="portlet-title">
            <div class="caption">
                <span class="caption-subject font-dark">Ebay aggregates</span>
            </div>
            <div class="actions">
                {!! Form::open(['route' => ['book.recalculate', $book->id]]) !!}
                {!! Form::submit('Recalculate', ['class' => 'btn btn-primary']) !!}
                {!! Form::close() !!}
            </div>
        </div>
        <div class="portlet-body">
            @if(isset($book->aggregates))
                <span class="aggregate">Max price <span class="label label-info">{{ $book->book_currency->format( $book->aggregates['max_price']) }}</span></span>
                <span class="aggregate">Avg price <span class="label label-info">{{ $book->book_currency->format( $book->aggregates['avg_price'] ) }}</span></span>

                <span class="aggregate">Max II+ <span class="label label-info">{{ $book->book_currency->format( $book->aggregates['max_2_price']) }}</span></span>
                <span class="aggregate">Average I <span class="label label-info">{{ $book->book_currency->format( $book->aggregates['avg_1_price']) }}</span></span>
                <span class="aggregate">Average II+ <span class="label label-info">{{ $book->book_currency->format( $book->aggregates['avg_2_price']) }}</span></span>
            @endif
        </div>
    </div>

    <table class="table table-striped table-bordered">
        <tr>
            <th>Channel</th>
            <th>Group</th>
            <th>Function</th>
            <th>Suggested sale price</th>
        </tr>
        <tbody>
        @foreach ($items as $item)
            @foreach($item['functions'] as $function)
            <tr>
                <td>
                    {{ $item['name'] }}
                </td>
                <td>
                    {{ $item['groupName'] }}
                </td>
                <td>
                    {{ $function['name'] }}
                </td>
                <td>
                    {{ $function['suggested_sale_price'] }}
                </td>
            </tr>
            @endforeach
        @endforeach
        </tbody>
    </table>
@endsection

resources/views/book/create.blade.php
@extends('layouts.default')

@section('content')

    <div class="page-bar">
        @include('parts.breadcrumbs', ['breadcrumbs' => [
            ['label' => 'Books', 'link' => route('book.index')],
            'Create',
        ]])
    </div>

    <h3>Create</h3>

    {!! Form::open(['route' => 'book.store', 'files'=>true]) !!}
    @include('book._form')
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    {!! Form::close() !!}
@endsection

resources/views/book/edit.blade.php
@extends('layouts.default')

@section('content')

    <div class="page-bar">
        @include('parts.breadcrumbs', ['breadcrumbs' => [
            ['label' => 'Books', 'link' => route('book.index')],
            'Edit',
        ]])
    </div>

    <h3>Edit</h3>

    {!! Form::model($model, ['method' => 'PATCH', 'route' => ['book.update', $model->id], 'files'=>true]) !!}
    @include('book._form')
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    {!! Form::close() !!}

@endsection

resources/views/book/show.blade.php
@extends('layouts.default')

@section('content')
    <div class="page-bar">
        @include('parts.breadcrumbs', ['breadcrumbs' => [
            ['label' => 'Books', 'link' => route('book.index')],
            'Info'
        ]])
    </div>

    <h3>{{ $model->title }}</h3>
    <div class="actions par">
        <a href="{{ route('book.edit', $model->id) }}" class="btn btn-primary">Edit</a>

        {!! Form::open([
            'method' => 'DELETE',
            'route' => ['book.destroy', $model->id]
        ]) !!}
        {!! Form::submit('Delete', ['class' => 'btn btn-danger confirm', 'data-confirm'=>'Delete item?']) !!}
        {!! Form::close() !!}
        <a href="{{ route('book.addCopy', $model->id) }}" class="btn btn-primary">Add a copy</a>

        <a href="{{ route('keyword.index', $model->id) }}" class="btn btn-default">Keywords</a>
        <a href="{{ route('ebayItem.index', $model->id) }}" class="btn btn-default">eBay: Completed search</a>
        <a href="{{ route('ebayItem.liveSearch', $model->id) }}" class="btn btn-default">eBay: Live search</a>
        @if($model->getISBN() || $model->asin)
        <a href="{{ route('amazonData.index', $model->id) }}" class="btn btn-default">Amazon data</a>
        @endif

        <a href="{{ route('book.indexCalculation', $model->id) }}" class="btn btn-default">Calculations</a>
    </div>

    <table class="table table-striped table-bordered">
        <tr>
            <th>ID</th>
            <td>{{ $model->id }}</td>
        </tr>
        <tr>
            <th>ISBN 10</th>
            <td>{{ $model->isbn_10 }}</td>
        </tr>
        <tr>
            <th>ISBN 13</th>
            <td>{{ $model->isbn_13 }}</td>
        </tr>
        <tr>
            <th>ASIN</th>
            <td>{{ $model->asin }}</td>
        </tr>
        <tr>
            <th>Cover price</th>
            <td>{{ $model->cover_price !== null ? $model->currency->format($model->cover_price) : '' }}</td>
        </tr>
        <tr>
            <th>Language</th>
            <td>{{ $model->language ? $model->language->name : null }}</td>
        </tr>
        <tr>
            <th>Publisher</th>
            <td>{{ $model->publisher ? $model->publisher->name : null }}</td>
        </tr>
        <tr>
            <th>Author</th>
            <td>{{ $model->author ? $model->author->name : null }}</td>
        </tr>
        <tr>
            <th>Title</th>
            <td>{{ $model->title }}</td>
        </tr>
        <tr>
            <th>Series</th>
            <td>{{ $model->series }}</td>
        </tr>
        <tr>
            <th>Year</th>
            <td>{{ $model->year }}</td>
        </tr>
        <tr>
            <th>Decade</th>
            <td>{{ $model->decade }}</td>
        </tr>
        <tr>
            <th>Special type</th>
            <td><i class="fa {{ $model->special_type_id ? 'fa-star' : 'fa-star-o' }}"></i></td>
        </tr>
        <tr>
            <th>Original year</th>
            <td>{{ $model->origin_year }}</td>
        </tr>
        <tr>
            <th>Origin title</th>
            <td>{{ $model->origin_title }}</td>
        </tr>
        <tr>
            <th>Notes</th>
            <td>{{ $model->notes }}</td>
        </tr>
        <tr>
            <th>Tags</th>
            <td>{{ implode(', ', $model->tagNames()) }}</td>
        </tr>
        <tr>
            <th>Images</th>
            <td>
                <div class="row">
                    @foreach($model->images as $index => $image)
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{{ $image->getUrl('thumb') }}"/>
                            </div>
                        </div>
                    @endforeach
                </div>
            </td>
        </tr>
        <tr>
            <th>Created at</th>
            <td>{{ $model->created_at }}</td>
        </tr>
        <tr>
            <th>Update at</th>
            <td>{{ $model->updated_at }}</td>
        </tr>
    </table>

@endsection